

id_12 <- fread("E:/purges_12_16_20/id/ID-2012-1/VoterData.txt") %>% 
  select(-V58)

colnames(id_12) <- c("VOTER ID",
                     "LAST NAME",
                     "FIRST NAME",
                     "MIDDLE NAME",
                     "SUFFIX",
                     "STREET NUMBER",
                     "STREET NAME",
                     "UNIT",
                     "STREET NAME 2",
                     "STREET NAME 3",
                     "CITY",
                     "STATE",
                     "ZIP CODE",
                     "ZIP4 CODE",
                     "MAILING STREET NUMBER",
                     "MAILING STREET NAME1",
                     "MAILING UNIT",
                     "MAILING STREET NAME2",
                     "MAILING STREET NAME3",
                     "MAILING CITY",
                     "MAILING STATE",
                     "MAILING ZIP CODE",
                     "MAILING ZIP4 CODE",
                     "MAILING COUNTRY",
                     "GENDER",
                     "AGE",
                     "REGISTRATION DATE",
                     "TELEPHONE NUMBER",
                     "COUNTY NAME",
                     "COUNTY PRECINCT",
                     "STATE LEGISLATIVE DISTRICT",
                     "CONGRESSIONAL DISTRICT",
                     "PARTY",
                     "ELECTION DATE 1",
                     "ELECTION NAME 1",
                     "VOTED 1",
                     "ELECTION DATE 2",
                     "ELECTION NAME 2",
                     "VOTED 2",
                     "ELECTION DATE 3",
                     "ELECTION NAME 3",
                     "VOTED 3",
                     "ELECTION DATE 4",
                     "ELECTION NAME 4",
                     "VOTED 4",
                     "ELECTION DATE 5",
                     "ELECTION NAME 5",
                     "VOTED 5",
                     "ELECTION DATE 6",
                     "ELECTION NAME 6",
                     "VOTED 6",
                     "ELECTION DATE 7",
                     "ELECTION NAME 7",
                     "VOTED 7",
                     "ELECTION DATE 8",
                     "ELECTION NAME 8",
                     "VOTED 8")
colnames(id_12) <- clean_names(id_12)

id_12 <- id_12 %>% 
  select(voter_id,
         last_name,
         first_name,
         middle_name,
         street_number, street_name,
         city,
         state,
         party,
         zip_code,
         gender,
         age,
         reg_date = registration_date,
         county = county_name) %>% 
  mutate(party = ifelse(party %in% c("Democratic", "Republican", "Unaffiliated"),
                        substring(party, 1, 1), "O"),
         dob = as.character(make_date(year = (2012 - age))),
         reg_date = as.character(as.Date(reg_date, "%m/%d/%Y"))) %>% 
  select(-age)

id_12 <- clean_streets(id_12, c("street_number", "street_name"))

###################
id_16 <- fread("E:/purges_12_16_20/id/ID-2017-1/VoterData.txt") %>% 
  select(-V58)

colnames(id_16) <- c("VOTER ID",
                     "LAST NAME",
                     "FIRST NAME",
                     "MIDDLE NAME",
                     "SUFFIX",
                     "STREET NUMBER",
                     "STREET NAME",
                     "UNIT",
                     "STREET NAME 2",
                     "STREET NAME 3",
                     "CITY",
                     "STATE",
                     "ZIP CODE",
                     "ZIP4 CODE",
                     "MAILING STREET NUMBER",
                     "MAILING STREET NAME1",
                     "MAILING UNIT",
                     "MAILING STREET NAME2",
                     "MAILING STREET NAME3",
                     "MAILING CITY",
                     "MAILING STATE",
                     "MAILING ZIP CODE",
                     "MAILING ZIP4 CODE",
                     "MAILING COUNTRY",
                     "GENDER",
                     "AGE",
                     "REGISTRATION DATE",
                     "TELEPHONE NUMBER",
                     "COUNTY NAME",
                     "COUNTY PRECINCT",
                     "STATE LEGISLATIVE DISTRICT",
                     "CONGRESSIONAL DISTRICT",
                     "PARTY",
                     "ELECTION DATE 1",
                     "ELECTION NAME 1",
                     "VOTED 1",
                     "PARTY VOTED 1",
                     "BALLOT TYPE 1",
                     "ELECTION DATE 2",
                     "ELECTION NAME 2",
                     "VOTED 2",
                     "PARTY VOTED 2",
                     "BALLOT TYPE 2",
                     "ELECTION DATE 3",
                     "ELECTION NAME 3",
                     "VOTED 3",
                     "PARTY VOTED 3",
                     "BALLOT TYPE 3",
                     "ELECTION DATE 4",
                     "ELECTION NAME 4",
                     "VOTED 4",
                     "PARTY VOTED 4",
                     "BALLOT TYPE 4",
                     "ELECTION DATE 5",
                     "ELECTION NAME 5",
                     "VOTED 5",
                     "PARTY VOTED 5",
                     "BALLOT TYPE 5",
                     "ELECTION DATE 6",
                     "ELECTION NAME 6",
                     "VOTED 6",
                     "PARTY VOTED 6",
                     "BALLOT TYPE 6",
                     "ELECTION DATE 7",
                     "ELECTION NAME 7",
                     "VOTED 7",
                     "PARTY VOTED 7",
                     "BALLOT TYPE 7",
                     "ELECTION DATE 8",
                     "ELECTION NAME 8",
                     "VOTED 8",
                     "PARTY VOTED 8",
                     "BALLOT TYPE 8")
colnames(id_16) <- clean_names(id_16)

id_16 <- id_16 %>% 
  select(voter_id,
         last_name,
         first_name,
         middle_name,
         street_number, street_name,
         city,
         state,
         party,
         zip_code,
         gender,
         age,
         reg_date = registration_date,
         county = county_name) %>% 
  mutate(party = ifelse(party %in% c("Democratic", "Republican", "Unaffiliated"),
                        substring(party, 1, 1), "O"),
         dob = as.character(make_date(year = (2012 - age))),
         reg_date = as.character(as.Date(reg_date, "%m/%d/%Y"))) %>% 
  select(-age)

id_16 <- clean_streets(id_16, c("street_number", "street_name"))

id_12$purged <- !(id_12$voter_id %in% id_16$voter_id)
dbWriteTable(db_full, name = "ID_12", value = id_12, overwrite = T, append = F)
rm(id_12)
###################
id_20 <- fread("E:/purges_12_16_20/id/ID-2020-1/VoterData.txt") %>% 
  select(-V58)

colnames(id_20) <- c("VOTER ID",
                     "LAST NAME",
                     "FIRST NAME",
                     "MIDDLE NAME",
                     "SUFFIX",
                     "STREET NUMBER",
                     "STREET NAME",
                     "UNIT",
                     "STREET NAME 2",
                     "STREET NAME 3",
                     "CITY",
                     "STATE",
                     "ZIP CODE",
                     "ZIP4 CODE",
                     "MAILING STREET NUMBER",
                     "MAILING STREET NAME1",
                     "MAILING UNIT",
                     "MAILING STREET NAME2",
                     "MAILING STREET NAME3",
                     "MAILING CITY",
                     "MAILING STATE",
                     "MAILING ZIP CODE",
                     "MAILING ZIP4 CODE",
                     "MAILING COUNTRY",
                     "GENDER",
                     "AGE",
                     "REGISTRATION DATE",
                     "TELEPHONE NUMBER",
                     "COUNTY NAME",
                     "COUNTY PRECINCT",
                     "STATE LEGISLATIVE DISTRICT",
                     "CONGRESSIONAL DISTRICT",
                     "PARTY",
                     "ELECTION DATE 1",
                     "ELECTION NAME 1",
                     "VOTED 1",
                     "PARTY VOTED 1",
                     "BALLOT TYPE 1",
                     "ELECTION DATE 2",
                     "ELECTION NAME 2",
                     "VOTED 2",
                     "PARTY VOTED 2",
                     "BALLOT TYPE 2",
                     "ELECTION DATE 3",
                     "ELECTION NAME 3",
                     "VOTED 3",
                     "PARTY VOTED 3",
                     "BALLOT TYPE 3",
                     "ELECTION DATE 4",
                     "ELECTION NAME 4",
                     "VOTED 4",
                     "PARTY VOTED 4",
                     "BALLOT TYPE 4",
                     "ELECTION DATE 5",
                     "ELECTION NAME 5",
                     "VOTED 5",
                     "PARTY VOTED 5",
                     "BALLOT TYPE 5",
                     "ELECTION DATE 6",
                     "ELECTION NAME 6",
                     "VOTED 6",
                     "PARTY VOTED 6",
                     "BALLOT TYPE 6",
                     "ELECTION DATE 7",
                     "ELECTION NAME 7",
                     "VOTED 7",
                     "PARTY VOTED 7",
                     "BALLOT TYPE 7",
                     "ELECTION DATE 8",
                     "ELECTION NAME 8",
                     "VOTED 8",
                     "PARTY VOTED 8",
                     "BALLOT TYPE 8")
colnames(id_20) <- clean_names(id_20)

id_20 <- id_20 %>% 
  select(voter_id,
         last_name,
         first_name,
         middle_name,
         street_number, street_name,
         city,
         state,
         party,
         zip_code,
         gender,
         age,
         reg_date = registration_date,
         county = county_name) %>% 
  mutate(party = ifelse(party %in% c("Democratic", "Republican", "Unaffiliated"),
                        substring(party, 1, 1), "O"),
         dob = as.character(make_date(year = (2012 - age))),
         reg_date = as.character(as.Date(reg_date, "%m/%d/%Y"))) %>% 
  select(-age)

id_20 <- clean_streets(id_20, c("street_number", "street_name"))

id_16$purged <- !(id_16$voter_id %in% id_20$voter_id)
dbWriteTable(db_full, name = "ID_16", value = id_16, overwrite = T, append = F)
dbWriteTable(db_full, name = "ID_20", value = id_20, overwrite = T, append = F)
